language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: ZejBnuwCZEj2rMz9+wBmmfXJwHxMrKoHAxgMb/Nzh9rzEr970cw+geSDNJZJmq8npp5DrdrEN107+j/qyT2wvGHjNftp+ddgnbnDBGXbgHXeIONIJFkN2PLDOfem+Rh8l2PcDXHs2rER+KmRg4DY4O/VLs6qqST4jmEhwrGeppWBaxIGh+/XGaphQBwofgsawSaq/mdAhYUl9Tl3OAZSsZAgBjsfdHv5zLBjNpg2KLWbJ6Nsrx/zlJvRtjb0Gsd1+u+lCgP8jFNVdI3MKqOxODcthOJtHPvF4C4tu0lqopP5E3dDjKN22Es9Rq3JyX+QieZXz3NIUvpNp13eqmFRBTYvfNwDlQG+nRP80nVQXvBYuuVkbYOb+3jTGfhfDYSXOeokgZDXz/ZPiZIHJcQDOmu5RhOBgn4nuA/dyAAEtNjJwAQHmEZgF4dO5GtxZpaV7oVPspk6Jqzizh7x8K6GU5b0lPYFg8Jn98P0P1DyVi3L3dBAiRWmqzRTLk4MPsRywHHuFOy6+FrRqfeb7ujewzz8u3pJc6puEvvgBUALKQEo56RLAqN2H+wBQyd3HSr0yjIbIU4dDhYPOB080ONS88PzqhNJuJFzZwnLla57U7qdI3dOKejPiB66KqSXoypv0+aYjanBGrLal2nyI+C4Ock+TqW2romN2dDwrWogwpE=
  app: sample-travis-heroku-repo
  on:
    repo: Saigonomai/sample-travis-heroku-repo
