language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: gUR4Oy2nqhQXaJoo46kFqN2RMTnZ0dxeukoZWFUlAiwDLwRDw/uZZgyqrbrJUldz8ak0Yx+yh0zv+a3iut22sKiF7aINcHQhrgVyxvnZbLFpGEwsAX5EqiuoTz0TWf1M93IayxzQrlJ5Y+OtXRxqkFzOSWPb5j66FjXYz9KX6UAA4+gwPW8PpgoUyVoFXnDzQc1p+1eOwdbUW05gPgTeHTENI2iNRrR9+Sebd6vE1yYSc2Em684VcTewWd9BXvwDG23tnZP5xrAV3d5OeKINLooeo5neaw9KHy73oMUSEFmeaDiJ8A2E3EY2r47vIE+tjEUlLLqCB+vZMIX45q+i4+FjrHRLBwrSczVZc7aYF3ICD4T9L6Xv+V8caATE97wmmDzxAIA50bPpSForqom4fmXvdV1ddE0gDmT3t4DWG0NAGcvK5PI4lZW3n+4T8LwYbrjX03sNyEuXEc+ECbvDEBFhZJVPovohw2mfSThfx3yfdp6ioX2zUiYwagMGKizRy2h+DsFVu5ahHrVqX9a0tu4tODz4G7ObMHt4UdAhhh7MJhPCyN5WyctzQI07pkndkRn7K4HIucU6Y1CxUq3CZLu1kAM6nxUyMSrHaZ8Yz+0l6saqFbt7SQtslXOdB1P0MFSJwb3nGBsOTq/ssA64KkFvRmWzSBCk2Px5SWDOLk8=
  app: sample-travis-heroku-repo
  on:
    repo: Saigonomai/sample-travis-heroku-repo
